services:
  # lib:
  #   container_name: lib
  #   build: ../lib
  #   image: remla23-team04/remla-lib-image
  model-training:
    container_name: model-training
    build: ../model-training
    image: remla23-team04/remla-model-training-image
  model-service:
    container_name: model-service
    build: ../model-service
    image: remla23-team04/remla-model-service-image
  app:
    container_name: app
    build: ../app
    image: remla23-team04/remla-app-image
    ports: 
      - 8080:5000
