apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: ghcr.io/remla23-team04/app:0.1.6
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: MODEL_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: model-service
                key: url
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: password
        ports:
          - containerPort: 5000       
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app-svc
spec:
  selector:
    app: app
  ports:
  - port: 5000
    name: http
    targetPort: 5000

---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  password: dGVhbTA0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: model-service
data:
  url: "http://model-service-service:5001"


